services:
  - type: web
    name: yopo-ai
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn app:app
      --bind 0.0.0.0:$PORT
      --worker-class gthread
      --workers 2
      --threads 4
      --timeout 300
      --graceful-timeout 30
      --preload
      --access-logfile -
      --error-logfile -
      --log-level info
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SAFE_CLEANUP_INTERVAL_MIN
        value: "30"
      # ✅ safe_cleanup.py와 키 일치 (DISK_* 대신 SAFE_*)
      - key: SAFE_SOFT_CAP_GB
        value: "9.5"
      - key: SAFE_HARD_CAP_GB
        value: "9.8"
      - key: SAFE_TRIGGER_GB
        value: "7.0"
      - key: MIN_FREE_GB
        value: "1.0"
      - key: MAX_LOG_AGE_DAYS
        value: "7"
      - key: KEEP_RECENT_MODELS_PER_SYMBOL
        value: "3"
      # 필요시 자동학습 끄기
      # - key: DISABLE_AUTO_TRAIN
      #   value: "1"
    healthCheckPath: /ping
